excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://postgod.github.io
title: Post-God
tagline: Thoughts on life after deconversion
description: Post-God is a chronicle of my thoughts on life after religion
paginate: 5
